app:
  jms:
    queue:
      workload: trainer-workload-queue.stg
    consumer:
      concurrency: 2-5

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: INFO