app:
  jms:
    queue:
      workload: ${TRAINER_WORKLOAD_QUEUE}
    consumer:
      concurrency: ${JMS_CONSUMER_CONCURRENCY:5-10}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.gym.crm: WARN