spring:
  application:
    name: workload-service

server:
  port: 8082
  servlet:
    context-path: /workload-service

app:
  api:
    base-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970