spring:
  application:
    name: workload-service
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:vm://localhost?broker.persistent=false}
    user: ${ACTIVEMQ_USER:gym-crm}
    password: ${ACTIVEMQ_PASSWORD:gym-crm}

server:
  port: 8082
  servlet:
    context-path: /workload-service

app:
  api:
    base-path: /api/v1
  jms:
    queue:
      workload: trainer-workload-queue
      dlq: ActiveMQ.DLQ
    redelivery:
      maximum-redeliveries: ${WORKLOAD_MESSAGE_MAX_REDELIVERIES:3}
      initial-delay-ms: ${WORKLOAD_MESSAGE_INITIAL_REDELIVERY_DELAY_MS:1000}
      delay-ms: ${WORKLOAD_MESSAGE_REDELIVERY_DELAY_MS:2000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970