spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gym-core-service
          uri: lb://gym-crm
          predicates:
            - Path=/api/v1/**
        - id: workload-service
          uri: lb://workload-service
          predicates:
            - Path=/workload-service/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true