spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: DEBUG