spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym
    username: gym
    password: gym
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gym.crm: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/